### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LEBMAP** [apolat2018/LSAT#2]
Please what is the error

Executing: prepare D:\Desktop\sss "D:\Desktop\MM NAB FINAL\BJ_MM_FINAL_Merge.shp" D:\Desktop\Nabatiye_Data\StudyArea.shp 150 70
Start Time: Sun Jun  6 20:32:50 2021
Running script prepare...
[u'rec_EQ.tif', u'rec_Faults1.tif', u'rec_flood.tif', u'rec_Geology.tif', u'rec_LUC.tif', u'rec_Rain.tif', u'rec_River1.tif', u'rec_Roads1.tif', u'rec_soil.tif']
Starting DATA PREPARATION...
9 raster data imported as parameter
Area is converting to Raster
Raster is converting to Point
PREPARING TRAIN AND VALIDATION DATA
Clipping landslides
landslide pixels is converting to point
Failed script prepare...

Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.8\Scripts\Preparing_Data.py", line 97, in <module>
    arcpy.SubsetFeatures_ga("erased_poi.shp","data_trn.shp","",no_ls_trn,"ABSOLUTE_VALUE")###random no landslide pixels is selecting as many as train landslide pixels
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\ga.py", line 1286, in SubsetFeatures
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000854: The value is out of the range from 1 to 2.14748e+09.
Failed to execute (SubsetFeatures).

Failed to execute (prepare).
Failed at Sun Jun  6 20:33:38 2021 (Elapsed Time: 47.14 seconds)

**Comment by apolat2018** [comment]
Original code is "arcpy.SubsetFeatures_ga(hey,"train_1.shp","test_1.shp",split_size,"PERCENTAGE_OF_INPUT")###Splitting landslides as %70 train and %30 test" in data preparation script. please check the parameters.

**Comment by LEBMAP** [comment]
I am doing a final year project for my university. The aim is produce a susceptibility map for about 1000 Km^2. The parameters are provided by my university. The problem is that I am not a programmer so debugging is hard for me. Can you help me in a way or another please? All the 12 parameters are TIF images having 150,150 as resolution.

**Comment by LEBMAP** [comment]
This is the drive link for the data I was provided with.

https://drive.google.com/drive/folders/1Ay-u8DQoWwpwsIjwGuyXhuMZ9W6WOB16?usp=sharing

**Comment by apolat2018** [comment]
I checked the data. Soil and aspect data were not reclassified. Please reclass all parameters. Some problem is not only about software. You have to prepare data conveniently for susceptibility analysis. If the parameter is not suitable please don't use it. Also, your resolution is too low. Why don't you use 12.5 or 30 m DEM? Please try to download high-resolution DEM data. Also, your landslide polygons shape is not like the original landslide shapes. Please draw carefully your landslide shape.

**Comment by LEBMAP** [comment]
Thank you a lot. I will try your solution.
