### ISSUE TITLE
Error to execute the Preparing_Data.py file

### ISSUE THREAD

**Issue by iamtekson** [apolat2018/LSAT#3]
I tried in your sample data. But it throws the following error.
```
Traceback (most recent call last):
  File "C:\Users\tek\Downloads\LSAT-master\Preparing_Data.py", line 61, in <module>
    arcpy.SubsetFeatures_ga(hey,"train_1.shp","test_1.shp",split_size,"PERCENTAGE_OF_INPUT")###Splitting landslides as %70 train and %30 test
  File "c:\program files (x86)\arcgis\desktop10.8\arcpy\arcpy\ga.py", line 1286, in SubsetFeatures
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000824: The tool is not licensed.
Failed to execute (SubsetFeatures).


Failed to execute (prepare).
```

**Comment by apolat2018** [comment]
Cause
There are two possible reasons for this issue:
The ArcGIS for Desktop version installed is not licensed for tools in an extension.
The extension the tools are in is not checked out in the script. If this is the case, the tool is not available for use in the Python environment.
Please check the link below.
https://support.esri.com/en/technical-article/000013100
