### ISSUE TITLE
Error in Logistic regression method

### ISSUE THREAD

**Issue by shakyaanice** [apolat2018/LSAT#4]
Dear Sir,

I prepared the sample data you provided and ran logistic regression method but it showed this error.

```
Traceback (most recent call last):
  File "C:\LSAT-master\LSAT-master\Logistic_Regression.py", line 14, in <module>
    from sklearn.linear_model import LogisticRegression
  File "C:\Python27\ArcGIS10.8\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "C:\Python27\ArcGIS10.8\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "C:\Python27\ArcGIS10.8\lib\site-packages\sklearn\utils\__init__.py", line 12, in <module>
    from .murmurhash import murmurhash3_32
  File "__init__.pxd", line 164, in init sklearn.utils.murmurhash
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 52, got 56

Failed to execute (LOGr).
Failed at Mon Mar 21 21:31:00 2022 (Elapsed Time: 0.12 seconds)


```

**Comment by apolat2018** [comment]
Please check the version of Scikit-learn. Python 2.7 supports the versions of Scikit-learn 0.20 and earlier. In this study, the version of 0.20.2 was installed.
