### ISSUE TITLE
ROC Plot fails for Frequency Ratio Method

### ISSUE THREAD

**Issue by Shelomoh1** [apolat2018/LSAT#5]
@apolat2018 I get the following error during the generation of the ROC Curve for the Frequency Ratio Method. The last but one value is a scientific notation (8.00640512409e-05); I am not sure if that's what caused the error, and I have no control over the generation of these values. How do I rectify this problem?

Start Time: Tue Jun 07 14:18:36 2022
Running script FRanalysis...
Analysis started
Starting Frequency Ratio Analysis...
Analysis finished
Susceptibility Map was created in D:\LSM\Results\FR folder as fr_sus raster file
ROC calculation is starting.....
Success rate is: 86.963695546
prediction rate is: 86.6727031059
101
[1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.999973311983, 0.999973311983, 0.999973311983, 0.999866559915, 0.999786495863, 0.999706431812, 0.99954630371, 0.999386175607, 0.999092607419, 0.998799039231, 0.998638911129, 0.998238590873, 0.997331198292, 0.996637309848, 0.995623165199, 0.994875900721, 0.993408059781, 0.99186015479, 0.990258873766, 0.988150520416, 0.985641846811, 0.982706164932, 0.979049906592, 0.975366960235, 0.971897518014, 0.967333867094, 0.962022951695, 0.955084067254, 0.947371230318, 0.939097945023, 0.930504403523, 0.921910862023, 0.912836936216, 0.900960768615, 0.88820389645, 0.87440619162, 0.859674406192, 0.844408860422, 0.825753936483, 0.805684547638, 0.783773685615, 0.761649319456, 0.74040565786, 0.71654657059, 0.691619962637, 0.663090472378, 0.636055511076, 0.606805444355, 0.576354416867, 0.548011742728, 0.518361355751, 0.487536696023, 0.453135842007, 0.418895116093, 0.384947958367, 0.353696290366, 0.323725647184, 0.295276220977, 0.268027755538, 0.237176407793, 0.209153989859, 0.184307445957, 0.163090472378, 0.140245529757, 0.11956231652, 0.100373632239, 0.0818254603683, 0.0645049372832, 0.0506805444355, 0.038217240459, 0.0259941286362, 0.0178542834267, 0.0111022151054, 0.00725914064585, 0.00416333066453, 0.00232185748599, 0.00130771283694, 0.000560448358687, 0.000266880170803, 8.00640512409e-05, 0.0]
Failed script FRanalysis...

Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.4\Scripts\LSAT-master\frequency_ratio.py", line 340, in <module>
    plt.plot(tot,tr,color="red",label=":Success Rate"+"("+str(f)+")")#success rate
  File "C:\Python27\ArcGIS10.4\lib\site-packages\matplotlib\pyplot.py", line 3092, in plot
    ax = gca()
  File "C:\Python27\ArcGIS10.4\lib\site-packages\matplotlib\pyplot.py", line 828, in gca
    ax =  gcf().gca(**kwargs)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\matplotlib\figure.py", line 1274, in gca
    return self.add_subplot(1, 1, 1, **kwargs)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\matplotlib\figure.py", line 937, in add_subplot
    if isinstance(args[0], SubplotBase):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

Failed to execute (FRanalysis).
Failed at Tue Jun 07 14:18:51 2022 (Elapsed Time: 15.12 seconds)

**Comment by Shelomoh1** [comment]
Restarting ArcGIS software solved the issue.
